// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwooiAboCDeGIz-JX2P51o-UDJudECoQ0',
    appId: '1:95669286180:web:72a9cc066007aa9f012fb1',
    messagingSenderId: '95669286180',
    projectId: 'nischalfancystorenfs',
    authDomain: 'nischalfancystorenfs.firebaseapp.com',
    storageBucket: 'nischalfancystorenfs.firebasestorage.app',
    measurementId: 'G-BDSK0TSVG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg-umA4CQBOfDuXUQjaU5NFJ2kNbXetHE',
    appId: '1:95669286180:android:78b31d8d9e1d9217012fb1',
    messagingSenderId: '95669286180',
    projectId: 'nischalfancystorenfs',
    storageBucket: 'nischalfancystorenfs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCetbfuOhTbuO0PHK4vW80CrhoLPf5wyQc',
    appId: '1:95669286180:ios:25cc38facd92eca5012fb1',
    messagingSenderId: '95669286180',
    projectId: 'nischalfancystorenfs',
    storageBucket: 'nischalfancystorenfs.firebasestorage.app',
    iosClientId: '95669286180-7alpt5ahdt2u5d72q5359rumppfiu5er.apps.googleusercontent.com',
    iosBundleId: 'com.example.nfs.nfsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCetbfuOhTbuO0PHK4vW80CrhoLPf5wyQc',
    appId: '1:95669286180:ios:25cc38facd92eca5012fb1',
    messagingSenderId: '95669286180',
    projectId: 'nischalfancystorenfs',
    storageBucket: 'nischalfancystorenfs.firebasestorage.app',
    iosClientId: '95669286180-7alpt5ahdt2u5d72q5359rumppfiu5er.apps.googleusercontent.com',
    iosBundleId: 'com.example.nfs.nfsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwooiAboCDeGIz-JX2P51o-UDJudECoQ0',
    appId: '1:95669286180:web:195003f268e58cca012fb1',
    messagingSenderId: '95669286180',
    projectId: 'nischalfancystorenfs',
    authDomain: 'nischalfancystorenfs.firebaseapp.com',
    storageBucket: 'nischalfancystorenfs.firebasestorage.app',
    measurementId: 'G-YL9W91KM6M',
  );

}